version: '3.9'

services:
  sierra:
    build: .
    container_name: sierra_react
    restart: always
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sierra.rule=Host(`sierra.acadsoft.com.br`)"
      - "traefik.http.routers.sierra.entrypoints=websecure"
      - "traefik.http.routers.sierra.tls.certresolver=letsencrypt"

networks:
  traefik-network:
    external: true
